Fix error C2561 when using PlatformToolset v100.
* Change the defination of UNDEFINED
* It seems that PlatformToolset doesn't understand the code following throw is unreachable. So it throw error C2561.
* Add a fake `__asm ret` to trick compiler to get a successful build.